### ISSUE TITLE
ECHAM-6.3.05p2 Runtime Error with Shared Libraries

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#154]
**Describe the bug**
When running `AWIESM-2.1` on Ollie, I immediately get an error:
```
  27: /work/ollie/pgierz/test_esmtools/experiments/forced_init_test_003/run_20000101-20001231/work/./echam6: error while loading shared libraries: libsupport.so.0: cannot open shared object file: No such file or directory
```

I preformed a clean install of all the components this morning, and re-installed the model from scratch.

**To Reproduce**
You can use this runscript to reproduce the problem:
```yaml
general:
    setup_name: "awiesm"
    version: "2.1"
    compute_time: "01:00:00"
    initial_date: "2000-01-01"
    final_date: "2300-12-31"
    base_dir: "/work/ollie/pgierz/test_esmtools/experiments/"
    nmonth: 0
    nyear: 1

awiesm:
    postprocessing: false
    model_dir: "/work/ollie/pgierz/test_esmtools/model_codes/awiesm-2.1/"
    scenario: "PALEO"

echam:
    nproca: 24
    nprocb: 18
    nprocar: 24
    nprocbr: 18
    npromar: 8
    restart_rate: 1
    restart_unit: "years"

fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/dsidoren/input/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
    lresume: 0
```

**System (please complete the following information):**
 - Supercomputer: ollie
 - Version:
```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.6 (development install, on branch: release, describe=v4.2.6-1-g4116b68)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.5.0
```

**Additional Info**

Probably, this has something to do with one of the modules on ollie? `AWIESM-2.1` is the only model that uses `ECHAM-6.3.05p2 with concurrent radiation` and configure/autotools rather than CMake. I can test and see if this happens with the regular AWICM-2.

**Comment by pgierz** [comment]
This problem does **not** occur with the regular `AWICM-2.0` model.

**Comment by dbarbi** [comment]
Hey Paul, Cray machines don't support dynamic linking, please make sure you
link statically only

Paul Gierz <notifications@github.com> schrieb am Fr., 9. Okt. 2020, 13:11:

**Comment by pgierz** [comment]
How do I get autotools to do that? Add `-all-static` `$FCFLAGS`?

**Comment by pgierz** [comment]
Problem (sort of) solved. I reverted all the changes made in `mh-linux`, and now the model runs on ollie. Not sure what we are going to do about compiling on mistral, though....

**Comment by dbarbi** [comment]
Sorry, can't check as I have to build a toy train track now. I think it
needs to go into LDFLAGS. Natalja knows.

Paul Gierz <notifications@github.com> schrieb am Fr., 9. Okt. 2020, 13:59:

**Comment by fernandadialzira** [comment]
@pgierz I have been having the same problem, but doing a historical simulation under mistral. I will try to install the esm_tools and model under ollie and see if it works

**Comment by pgierz** [comment]
Hi Fernanda,

I just mailed you about this I believe. If it is the same problem, we can look on Wednesday. Otherwise I would suggest to open a new issue so it's on the radar of more people. I don't think the "closed issues" pop up. 

In any case, the problem I described here was with an old version of esm, I would be very surprised if what I had back then is still an active problem with the new version you have.

**Comment by christian-stepanek** [comment]
"In any case, the problem I described here was with an old version of esm, I would be very surprised if what I had back then is still an active problem with the new version you have."

Well, it just happened to me @pgierz, compiled on mistral with esm tools v 6.1.8
```
54: /mnt/lustre02/work/ab0246/a270061/esm_experiments_v6/PI_ref/run_24000101-24001231/work/./echam6: error while loading shared libraries: libsupport.so.0: cannot open shared object file: No such file or directory
```
Maybe the issue should be reopened? If so, I do not have sufficient authority to do so.

**Comment by denizural** [comment]
Good morning @christian-stepanek,
I just reopened the issue and checked the echam binary via `$ ldd echam6 | grep --color "not found"`
```
libsupport.so.0 => not found
libcdi.so.0 => not found
libpnetcdf.so => not found
libyaxt.so.1 => not found
libyaxt_c.so.1 => not found
```
As you can see, it is not only libsupport but other libraries too. I will have a quick look now.

PS: could you also write how you built Echam with ESM-Tools? (eg. the exact `esm_master` command)

**Comment by christian-stepanek** [comment]
@denizural Here the details:

In esm-tools v6.1.8 I first downloaded the source code with the command
```
esm_master get-awiesm-2.1-wiso
```
Then I applied source code changes necessary for my simulation. Thereafter I compiled the modified model source code with the following command:
```
esm_master comp-awiesm-2.1-wiso
```
Thanks a lot for your help with this issue.

**Comment by christian-stepanek** [comment]
@denizural Just to note something that I forgot to mention: The executables were build with esm-tools_v6, whereas I tried to run the simulation with the predecessor version v5. The reason for this slightly alternative approach is that I have problems with esm_runscripts in esm-tools_v6.

**Comment by denizural** [comment]
Hi @christian-stepanek ,
I managed to solve the Echam missing library issue on Mistral. Here you can find a compile script to build echam:
`/mnt/lustre01/pf/a/a271096/Solutions/Christian_Stepanek/comp-echam-6.3.05p2-wiso_script_BACKUP.sh`

The resulting Echam binary contains all missing libraries:
```
    libsupport.so.0 => /home/a/a271096/Solutions/Christian_Stepanek/echam-6.3.05p2-wiso/lib/libsupport.so.0 (0x00002b6db6364000)
    libcdi.so.0 => /home/a/a271096/Solutions/Christian_Stepanek/echam-6.3.05p2-wiso/lib/libcdi.so.0 (0x00002b2aca95a000)
    libyaxt.so.1 => /home/a/a271096/Solutions/Christian_Stepanek/echam-6.3.05p2-wiso/lib/libyaxt.so.1 (0x00002b6d6d1ae000)
    libyaxt_c.so.1 => /home/a/a271096/Solutions/Christian_Stepanek/echam-6.3.05p2-wiso/lib/libyaxt_c.so.1 (0x00002b6d6d3dd000)
```

Could you please tell me what problems you are having so that you can't run AWIESM with Release 6?

---

I slight problem is with parallel NetCDF. This is a question to @pgierz . In ESM-Tools, we set the NetCDF to 
`/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-parallel-impi-intel14/`, eg.
`export NETCDFFROOT=/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-parallel-impi-intel14/`

and if you look at the library configuration
`/sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-parallel-impi-intel14//bin/nf-config --flibs`
yields
```
...
-L/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.0-impi-intel14/lib
...
```

However, the comp-script contains
`export LD_LIBRARY_PATH=/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.1-impi-intel14/lib/:$LD_LIBRARY_PATH`

Note the version difference 1.6.**0** vs 1.6.**1**. This might cause runtime problems due to library inconsistency. The resulting Echam binary has 

```
$ ldd echam6 | grep netcdf
    libsupport.so.0 => /home/a/a271096/Solutions/Christian_Stepanek/without_pnetcdf/echam-6.3.05p2-wiso/lib/libsupport.so.0 (0x00002b5cd3146000)
    libcdi.so.0 => /home/a/a271096/Solutions/Christian_Stepanek/without_pnetcdf/echam-6.3.05p2-wiso/lib/libcdi.so.0 (0x00002b5cd334f000)
    libnetcdff.so.6 => /sw/rhel6-x64/netcdf/netcdf_fortran-4.4.2-parallel-impi-intel14/lib/libnetcdff.so.6 (0x00002b5cd38a4000)
    libnetcdf.so.7 => /sw/rhel6-x64/netcdf/netcdf_c-4.3.2-gcc48/lib/libnetcdf.so.7 (0x00002b5cd3ecd000)
    libpnetcdf.so => not found
    libyaxt.so.1 => /home/a/a271096/Solutions/Christian_Stepanek/without_pnetcdf/echam-6.3.05p2-wiso/lib/libyaxt.so.1 (0x00002b5cd5c33000)
    libyaxt_c.so.1 => /home/a/a271096/Solutions/Christian_Stepanek/without_pnetcdf/echam-6.3.05p2-wiso/lib/libyaxt_c.so.1 (0x00002b5cd5e62000)
    libpnetcdf.so => /sw/rhel6-x64/netcdf/parallel_netcdf-1.6.0-impi-intel14/lib/libpnetcdf.so (0x00002b5cda12b000)
```

As you can see `libpnetcdf.so` is missing in the first place but its value is populated in the second encounter. What do you think about that?

**Comment by christian-stepanek** [comment]
Dear @denizural,

thanks a lot for your effort. I tried to recompile with the updated script, but run into the following error:
```
libtool:   error: error: cannot install 'libyaxt.la' to a directory not ending in /mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/lib
make[4]: *** [Makefile:654: install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/yaxt-0.5.2/src'
make[3]: *** [Makefile:890: install-am] Error 2
make[3]: Leaving directory '/mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/yaxt-0.5.2/src'
make[2]: *** [Makefile:884: install] Error 2
make[2]: Leaving directory '/mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/yaxt-0.5.2/src'
make[1]: *** [Makefile:540: install-recursive] Error 1
make[1]: Leaving directory '/mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/yaxt-0.5.2'
make: *** [Makefile:520: install-recursive] Error 1
```
I do not really understand what is happening here as the directory /mnt/lustre01/pf/a/a270061/esm_tools_v6/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/lib exists and is, as far as I can see, writable.

Should I fully clean the previous installation before compiling? If so, shall I compile fesom2 and echam6 individually via the provided compile scripts rather than employing esm_master comp-awiesm-2.1-wiso?

Any further ideas?
Thanks a lot.
Christian

**Comment by denizural** [comment]
Hi @christian-stepanek,
I just built awiesm-2.1-wiso on Mistral via `esm_master install-awiesm-2.1-wiso` using the esm-tools release 6. Let's check the Echam binary:
```
$ ldd echam6 | grep yaxt
    libyaxt.so.1 => /mnt/lustre01/pf/a/a271096/Solutions/Christian_Stepanek/with_esm_tools/awiesm-2.1-wiso/echam-6.3.05p2-wiso/lib/libyaxt.so.1
    libyaxt_c.so.1 => /mnt/lustre01/pf/a/a271096/Solutions/Christian_Stepanek/with_esm_tools/awiesm-2.1-wiso/echam-6.3.05p2-wiso/lib/libyaxt_c.so.1
```

So, it looks like awiesm is OK.

Could you please show me how you are building awicm? Also what are the changes you are making on Echam? If you are changing the Makefiles then I need to have a look at that.

**Comment by christian-stepanek** [comment]
Dear @denizural,
yes, in principle I follow your example for installation of the model. The only difference is that I split the install command into two parts - a get part and a compile part - reason is that I need to modify the source code prior to compiling.

I also figured out now what is the source of the problem. It is actually quite stupid, but - well.

To explain what I am doing: I have to implement various source code changes to create an ensemble of simulations. For each simulation in need separate binaries that each include a specific source code change. My method was to get the model code, change the sources as needed, compile the model code. Getting awiesm-2.1-wiso with esm_master will always lead to a model folder that has exactly the name of the model version, unless there are some secret parameters lile "target-folder" that I am not aware of. To keep track of what I have after compiling I just renamed the whole model folder to reflect the change of the source code in the model folder name - eg.:
```
mv awiesm-2.1-wiso awiesm-2.1-wiso_mixing_test_1
```
And that is indeed the problem: The path of the dynamic libraries is apparently coded with its absolute location - once I rename (or move) the folder with the compiled model, the shared library is not found anymore. Oh my!

This could only be avoided by either having shared libraries being linked statically instead, or by having the shared library path in the linked executable being replaced by a relative path.

So, as I assume none of these alternatives is easily implemented, I must follow a different approach for keeping track of the various model versions - e.g. I have to create separate already properly named model folders into which then I get and compile the model code, keeping the standard name of the model version.

Indeed it is difficult to comprehend how many pitfalls appear due to the fact that one has dynamically linked libraries in the binaries. Not sure whether others may have fallen into that trap.

@pgierz If we ever want to realize your idea of having a model pool with precompiled standard executables, then we really need to tackle the shared library issue - once you move the binary or rename its folder, the executable it is essentially broken - kind of like a fragile China vase. :o/

**Comment by christian-stepanek** [comment]
Addendum: There is only a small number of shared libraries in awiesm-2.1-wiso that are afflicted by the above described problem. These are:

- libsupport.so.0
- libcdi.so.0
- libyaxt.so.1
- libyaxt_c.so.1

All the other shared libraries reside further down the file system tree in system-related paths and will not be moved together with the model.

libpnetcdf.so seems to be an interesting case in that it is available twice in echam6 - appears to be linked twice, and one instance is not found:

libpnetcdf.so => not found
libpnetcdf.so => /sw/rhel6-x64/netcdf/parallel_netcdf-1.6.0-impi-intel14/lib/libpnetcdf.so (0x00002b302665d000)

Not sure whether this is something one may want to change.

**Comment by fernandadialzira** [comment]
Dear @pgierz and @denizural,

I am also just now working with `awiesm-2.1-wiso` and I followed initially the same approach as @christian-stepanek, with the difference that I am working on ollie and only using esm-tools 6 branch release. So I started the installation by using `esm_master get-awiesm-2.1-wiso`, changing just one line from `<echam_folder>/src/src_jsbach3/mo_hydrology.F90` and running `esm_master comp-awiesm-2.1-wiso`. 

Long story short, by trying `$ ldd echam6 | grep --color "not found"` I get several missing libraries as well:

```
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libifport.so.5 => not found
	libifcoremt.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libmkl_intel_thread.so => not found
	libiomp5.so => not found
	libifport.so.5 => not found
	libifcoremt.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
```

Which decrease to those below if I change the name of the model, as Christian revealed.

```
	libsupport.so.0 => not found
	libcdi.so.0 => not found
	libyaxt.so.1 => not found
	libyaxt_c.so.1 => not found
	libifport.so.5 => not found
	libifcoremt.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libintlc.so.5 => not found
	libimf.so => not found
	libsvml.so => not found
	libirng.so => not found
	libintlc.so.5 => not found
	libmpi.so.12 => not found
```

I tested simulations for both cases and I get the same kind of error:

```
echam6:165108 terminated with signal 11 at PC=63481f SP=7fffffed8a30.  Backtrace:
255: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_16/run_20000101-20001231/work/./echam6[0x63481f]
384: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_16/run_20000101-20001231/work/./echam6[0x63481f]

```

In order to get more information about this error, I used export `$FCFLAGS="-g -traceback"` and tried recompiling the model with `esm_master recomp-awiesm-2.1-wiso` or `esm_master comp-awiesm-2.1-wiso`, I always get this error:

```
echam/mo_couple.f90(520): error #6404: This name does not have a type, and must have an explicit type.   [NFLDO2A]
       DO jfld = 1,nfldo2a
-------------------^
echam/mo_couple.f90(558): error #6404: This name does not have a type, and must have an explicit type.   [NFLDA2O]
       DO jfld = 1,nflda2o
-------------------^
compilation aborted for echam/mo_couple.f90 (code 1)
make[2]: *** [echam/mo_couple.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/work/ollie/fmatos/mis3/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/work/ollie/fmatos/mis3/model_codes/awiesm-2.1-wiso/echam-6.3.05p2-wiso/src'
make: *** [all-recursive] Error 1
Traceback (most recent call last):
  File "/home/ollie/fmatos/.local/bin/esm_master", line 8, in <module>
    sys.exit(main())
  File "/work/ollie/fmatos/mis3/software/github.com/esm-tools/esm_tools/src/esm_master/cli.py", line 103, in main
    main_flow(parsed_args, target)
  File "/work/ollie/fmatos/mis3/software/github.com/esm-tools/esm_tools/src/esm_master/esm_master.py", line 106, in main_flow
    user_task.execute(ignore_errors)  # env)
  File "/work/ollie/fmatos/mis3/software/github.com/esm-tools/esm_tools/src/esm_master/task.py", line 494, in execute
    subprocess.run(
  File "/work/ollie/fmatos/mis3/.local/opt/miniconda/envs/mis3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,subprocess.CalledProcessError: Command '['./comp-echam-6.3.05p2-wiso_script.sh']' returned non-zero exit status 2.
```

So after I tried to install the model with `esm_master install-awiesm-2.1-wiso` and when I run again `$ ldd echam6 | grep --color "not found"`, I get the same missing libraries as before. And after trying to recompile the model after making the changes I need, it did not work either way.
It is also worth noting that I got the same sequence of errors/missing libraries while trying the same protocol with awiesm-2.1-gamma.

**Comment by denizural** [comment]
@fernandadialzira, I am looking at this right now. I will edit this message later on

**Comment by mandresm** [comment]
That's very strange, I just got `awiesm-2.1-wiso` to build and run a monthly simulation with 3 restarts:
Path to experiment: /work/ollie/mandresm/testing/run/awiesm/PI_ctrl_awiesm-2.1-wiso/restart/
Path to the freshly compiled awiesm: /work/ollie/mandresm/testing/comp/awiesm/awiesm-2.1-wiso

**Comment by mandresm** [comment]
@fernandadialzira , can you let me know which branch of `esm_tools` are you using? I'm on `fix/awiesm_default_variant`, which is almost identical to `release`, with the difference of the `variant` fixes, which should not affect compilation.

**Comment by fernandadialzira** [comment]
I tried the experiments still when on release, but judging by the error I got with the missing libraries, I have not tried a run with the `fix/awiesm_default_variant` branch. Deniz told me he is looking into it and will probably give me some insight soon. 
How did you build `awiesm-2.1-wiso`? With `esm_master get and comp` or `install`? I tried both ways and I got the same missing libraries and the same error in the simulation.

The weird thing is that you get the same missing libraries under the /bin/ folder of the freshly compiled `awiesm-2.1-wiso` but still your simulation starts, while mine stops with the same error.

**Comment by mandresm** [comment]
I built using `get` and then `comp` cause that's the way my testing software works, but I have built one week ago with `install` and that was not a problem either.

**Comment by denizural** [comment]
Ok, I successfully built `awiesm-2.1-wiso` on Ollie (esm_tools, version 6.1.10)
The missing libraries on Ollie could be an exceptional case since as Dirk said earlier, dynamic linking is not possible on this architecture. But no worries, here is the solution:

```shell
$ ldd awiesm-2.1-wiso/bin/echam6 | grep "not found" | wc -l    # 28 libraries are not found
$ module load intel.compiler
$ ldd awiesm-2.1-wiso/bin/echam6 | grep "not found" | wc -l    # now it is 0
```
So, all you need to do is loading the correct environment and this is what `esm_runscripts` does.

PS: build commands:
```shell
esm_master get-awiesm-2.1-wiso
esm_master comp-awiesm-2.1-wiso &>compile_1.log
```

**Comment by mandresm** [comment]
So it also compiles for you out of the box @denizural ? you did not need to change anything right?

**Comment by mandresm** [comment]
Maybe there is a conflict with an already loaded module? When I run `module list` I get: 
```
Currently Loaded Modulefiles:
 1) python3/3.7.7_intel2020u2(default)   2) git/2.13.1   3) direnv/2.30.3
```

So very minimal output. @fernandadialzira , @denizural can you post yours?

**Comment by denizural** [comment]
@mandresm, mine is 
```
1) git/2.13.1   2) python3/3.7.7_intel2020u2(default)
```
But this should not change anything since `esm_master` calls `module purge` at the top and unloads everything. Yes, I did not change anything and also verified that `mo_couple.f90` that failed in @fernandadialzira 's case actually compiles. The variable `nfldo2a` should come from `mo_control.f90` because `mo_couple.f90` takes when it is compiled with FESOM:
```fortran
51 #ifdef __cpl_feom
52   USE mo_control,         ONLY: nflda2o,nfldo2a
53 #endif
```

**Comment by pgierz** [comment]
Alright, so, before I dive too deep into this: @denizural you are working on the library issue? Then I will hold back. My only hint is: we should think about statically linking everything unless there are good reasons (memory overhead, wall time, usw) not to do this.

**Comment by mandresm** [comment]
I am starting to suspect this might be a problem with the `direnv`, although @denizural is right, we purge the modules so that should not be a problem. @fernandadialzira , can you let us know the path to your `.envrc`?

I'll hold as well if @denizural is working on it.

**Comment by pgierz** [comment]
As info for @denizural: `direnv` does not really do any magic. It just starts a subshell, which should inherit everything from above, the fact that you can trick this thing into creating a unique Python environment should (hopefully) not have an influence on compile-time things, but admittedly, it is one extra layer of complication to be aware of.

**Comment by pgierz** [comment]
> @mandresm, mine is
> 
> ```
> 1) git/2.13.1   2) python3/3.7.7_intel2020u2(default)
> ```
> 
> But this should not change anything since `esm_master` calls `module purge` at the top and unloads everything. Yes, I did not change anything and also verified that `mo_couple.f90` that failed in @fernandadialzira 's case actually compiles. The variable `nfldo2a` should come from `mo_control.f90` because `mo_couple.f90` takes when it is compiled with FESOM:
> 
> ```fortran
> 51 #ifdef __cpl_feom
> 52   USE mo_control,         ONLY: nflda2o,nfldo2a
> 53 #endif
> ```

The fact that variables required for a coupling routine designed specifically to couple to "any" ocean is hidden behind a compiler directive specifying `FESOM` still eludes my own personal sense of logic, but na ja, that's how it is I guess. Let's not go into the weeds of FORTRAN too much.

**Comment by fernandadialzira** [comment]
Hi! Sorry for the late response

@mandresm 
Mine is only:
```
1) git/2.13.1

```
As of this:
> I am starting to suspect this might be a problem with the `direnv`, although @denizural is right, we purge the modules so that should not be a problem. @fernandadialzira , can you let us know the path to your `.envrc`?
> 


I am not using direnv anymore, as it seemed to be the cause of some issues last time. To do so I just renamed my `.envrc` file. However, should I have done something else to actually delete the `direnv`? @pgierz do you suggest something?

@denizural 
> PS: build commands:
> 
> ```shell
> esm_master get-awiesm-2.1-wiso
> esm_master comp-awiesm-2.1-wiso &>compile_1.log
> ```

I will try then a clean installation with these commands and I will run the experiment. This time already on the `fix/awiesm_default_variant` branch to save some time on the tests, as it only changes a minor part of the `awiesm-2.1.yaml`. Thank you!

**Comment by pgierz** [comment]
Renaming the `.envrc` file should turn off the `direnv`, and therefore revert to whichever `esm-tools` you have installed in `${HOME}/.local/`

**Comment by denizural** [comment]
@pgierz and all,
I made a toy matrix multiplication example using Intel MKL on both Ollie and Mistral to see how these different systems behave. Here are the observations:

- When you compile a code with dynamic libraries (.so), they run straightforward on Mistral but you need to load the required modules (which set `LD_LIBRARY_PATH`, ...) on Ollie. Otherwise, they don't run on Ollie.
- It is possible to overcome this via static linking but it increases the executable size (x10) which is not a very desirable thing.
- So, if Ollie complains about not being able to find the libraries, then it is because of the inconsistent environment loading.

**Comment by pgierz** [comment]
@denizural excellent, we are then one step closer. This for me does not however explain the issue @christian-stepanek and @fernandadialzira reported: simply renaming or moving the binary leads to errors.

For point 1: Not sure I fully understand. Shouldn't the `LD_LIBRARY_PATH` behave identically on both machines?

For point 2: increasing the binary size is suboptimal, I would say. This *might* be solved via a shared model pool, but this is something Christian and I need to discuss.

For point 3: that makes sense (inconsistent environment), and if this is not occurring by default I would here point to "user error" (sorry users), but we should try to make sure that this is correctly handled as far as possible on the tools side.

**Comment by fernandadialzira** [comment]
@denizural so I rebuilt the model and the log of compilation process you can find in `/work/ollie/fmatos/mis3/run_configs_testing/compile_1.log`

After compiling I went to the binary folder and used `ldd echam6 | grep --color "not found"` and no missing libraries were found.

However, after running the simulation I get the same error still (`/work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/log/glac1d21_classic_bootstrap_001_18_awiesm_compute_20000101-20001231_13959682.log`):

```
echam6:134385 terminated with signal 11 at PC=6317e4 SP=7fffffeed9a0.  Backtrace:
384: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x41175e]
292: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x8f005b]
408: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x447a30]
256: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x81c775]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x63481f]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x5eb527]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x60272d]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x6100e4]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x607af0]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x8d084e]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0x81c775]
 76: /work/ollie/fmatos/mis3/bootstrap_testing/glac1d21_classic_bootstrap_001_18/run_20000101-20001231/work/./echam6[0xbd343e]
384: /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaab24c8445]
```
Which is not a message that gives much information anyway.

On the account of point 3 of the inconsistent environment, it is always an option, so: @pgierz should I create a full clean installation of mis3/esm_tools without the `.envrc` and the `environment.yml` files? I normally run the models under my environment, but I tried the simulation with this environment also deactivated. When the environment is deactivated it only increases the submission time, but I still get this error. 

In any case, there is also the submission log here `/work/ollie/fmatos/mis3/run_configs_testing/submit_test18.log`

**Comment by pgierz** [comment]
Well, if I have learned nothing else in my life, it is "turn it off, hit it with a hammer, turn it on, try again" 😉 (Please don't hit your computer with a hammer, even if this may feel very satisfying in the moment)

Fernanda, did I show you how to turn on tracebacks yet? You need to add `-g -traceback` to the compile time flags. That will give more info than just some random memory address

**Comment by denizural** [comment]
@pgierz,
What I see is that Mistral and Ollie behave differently in runtime (maybe you can ask Natalja or Malte about that). When `LD_LIBRARY_PATH` is empty Mistral shows the dynamically linked libraries in `ldd`. Ollie says `not found` but only shows the location of the library when you set `LD_LIBRARY_PATH`. Eg.

```
$ ldd dgemm_example | grep libmkl_core
        libmkl_core.so => not found

$ module load intel.compiler; ldd dgemm_example | grep libmkl_core
        libmkl_core.so => /global/AWIsoft/intel/2018/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64/libmkl_core.so
```

**Comment by pgierz** [comment]
@denizural: Good to know, but not particularly surprising. A toy example is not really useful here, since we want to see what happens when a user actually tries to run the model. The `module load intel.compiler` should anyway be happening in the generated run file. The question remains: why does it break when a user simply renames their binary (or more precisely, their model folder)

**Comment by christian-stepanek** [comment]
I think the reason "why" has been answered by me at these posts:
https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1048309591
https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1048316929
Let me know if there is more help needed from my side.

If one can solve this issue with a set LD_LIBRARY_PATH, then okay. I am just not knowledgeable enough to foresee if this is practically feasible if shared libraries are residing a very different locations.

Again, my interpretation of the problem was that ECHAM6 crashes due to missing libraries because some of them (see my list above) are actually located within the model directory - hence, if you move the model directory, ECHAM6 will not find the shared libraries anymore. In case these shared libraries are moved to a permanent location, a model pool or a system path for example, then one can compile the model and move it around as much as one wants.

Alternatives for shared libraries within the model folder would be to link these dynamically, but make sure that the path is set as a relative path (if that is possible, I do not know).

**Comment by fernandadialzira** [comment]
@pgierz 

> Well, if I have learned nothing else in my life, it is "turn it off, hit it with a hammer, turn it on, try again" wink (Please don't hit your computer with a hammer, even if this may feel very satisfying at the moment)
> 
> Fernanda, did I show you how to turn on tracebacks yet? You need to add `-g -traceback` to the compile time flags. That will give more info than just some random memory address

Yes, I did it as I detailed in this [post](https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1048969256) and Deniz also commented about it [here](https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1049859392) and you [here](https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1049877157).

As a last trial of this, I will try to run `$FCFLAGS="-g -traceback"` before compiling the model. Last time I could only make it work was by running this command, changing the `echam` remote to your gitlab repository (https://gitlab.awi.de/pgierz/echam6) instead of the normal repository (https://gitlab.awi.de/paleodyn/Models/echam6), and then compiling. I will try it last time, otherwise, I will try a full clean installation. As we have been trying several things over time with mis3, something may be causing conflicts and I believe it would be worth trying.

Update 01: with `$FCFLAGS="-g -traceback"` either with the gitlab/models or gitlab/pgierz repositories, I cannot compile with the same information given in [here](https://github.com/esm-tools/esm_tools/issues/154#issuecomment-1048969256). The logs of these compilations you can find in:

`/work/ollie/fmatos/mis3/model_codes/compile_FcFlagsTest.log`
`/work/ollie/fmatos/mis3/model_codes/compile_FcFlagsTest_PGRepo.log`

and the sequence of commands for (1) Model repository, (2) Paul repository:
(1)
```
$esm_master get-awiesm-2.1-wiso
$export FCFLAGS="-g -traceback"
$vim awiesm-2.1-wiso/echam-6.3.05p2-wiso/src/src_jsbach3/mo_hydrology.f90
$esm_master comp-awiesm-2.1-wiso &>compile_FcFlagsTest.log
```
(2)
```
$esm_master get-awiesm-2.1-wiso
$export FCFLAGS="-g -traceback"
$vim awiesm-2.1-wiso/echam-6.3.05p2-wiso/src/src_jsbach3/mo_hydrology.f90
$cd echam-6.3.05p2-wiso/
$git remote set-url origin https://gitlab.awi.de/pgierz/echam6
$esm_master comp-awiesm-2.1-wiso &>compile_FcFlagsTest.log
```

**Comment by pgierz** [comment]
Hello, I am going through old issues: can this one be closed?

**Comment by fernandadialzira** [comment]
From my side, yes. We identified that in my case the issue could be solved by changing the branch, and now there are new switches for bootstrap.
